version: '3'
services:
  migrations-stage:
    image: $DOCKER_TAG
    env_file:
      - $ENV
    command: npx prisma migrate reset 

  seed-stage:
    image: $DOCKER_TAG
    env_file:
      - $ENV
    command: sh -c "yarn seed-init && yarn seed-fake"
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
  
  seed-fake-stage:
    image: $DOCKER_TAG
    env_file:
        - $ENV
    command: yarn seed-fake
    restart: on-failure
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
      seed-stage:
        condition: service_completed_successfully
   

  app-cabinet-stage:
    image: $DOCKER_TAG
    container_name: SH-b-cabinet-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$CABPORT:3004"
    command: node ./dist/apps/cabinet/src/main.js
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
      seed-stage:
        condition: service_completed_successfully
      seed-fake-stage:
        condition: service_completed_successfully

  app-rating-stage:
    image: $DOCKER_TAG
    container_name: SH-b-rating-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$RATINGPORT:3005"
    command: node ./dist/apps/rating/src/main.js
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
      seed-stage:
        condition: service_completed_successfully
      seed-fake-stage:
        condition: service_completed_successfully

  app-employer-stage:
    image: $DOCKER_TAG
    container_name: SH-b-employer-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$EMPLOYERPORT:3006"
    command: node ./dist/apps/employer/src/main.js
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
      seed-stage:
        condition: service_completed_successfully
      seed-fake-stage:
        condition: service_completed_successfully
        
  app-mobile-stage:
    image: $DOCKER_TAG
    container_name: SH-b-mobile-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$MOBILEPORT:3007"
    command: node ./dist/apps/mobile/src/main.js
    depends_on:
      migrations-stage:
        condition: service_completed_successfully
      seed-stage:
        condition: service_completed_successfully
      seed-fake-stage:
        condition: service_completed_successfully