version: '3'
services:
  migrations:
    image: $DOCKER_TAG
    env_file:
      - $ENV
    command: npx prisma migrate deploy 

  seed:
    image: $DOCKER_TAG
    env_file:
      - $ENV
    command: yarn seed-init
    migrations:
            condition: service_completed_successfully

  app-cabinet:
    image: $DOCKER_TAG
    container_name: SH-b-cabinet-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$CABPORT:3000"
    command: node ./dist/apps/cabinet/src/main.js
    depends_on:
      migrations:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully

  app-rating:
    image: $DOCKER_TAG
    container_name: SH-b-raiting-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$RATINGPORT:3001"
    command: node ./dist/apps/rating/src/main.js
    depends_on:
      migrations:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully

  app-employer:
    image: $DOCKER_TAG
    container_name: SH-b-employer-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$EMPLOYERPORT:3002"
    command: node ./dist/apps/employer/src/main.js
    depends_on:
      migrations:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully
        
  app-mobile:
    image: $DOCKER_TAG
    container_name: SH-b-mobile-$CI_COMMIT_BRANCH
    restart: always
    env_file:
      - $ENV
    ports:
      - "$MOBILEPORT:3003"
    command: node ./dist/apps/mobile/src/main.js
    depends_on:
      migrations:
        condition: service_completed_successfully
      seed:
        condition: service_completed_successfully